custom_logo_url: "https://www.coriell.org/Content/Coriell_Logo_NewV3MDB1.webp"
module_order:
    - fastqc:
        name: 'FastQC (raw)'
        anchor: 'fastqc_raw'
        path_filters_exclude:
            - '*_val_1_fastqc.zip'
            - '*_val_2_fastqc.zip'
            - '*_trimmed_fastqc.zip'
            - '*_repaired_R1_fastqc.zip'
            - '*_repaired_R2_fastqc.zip'
            - '*_rmrRNA_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (trimmed)'
        anchor: 'fastqc_trimmed'
        path_filters:
            - '*_val_1_fastqc.zip'
            - '*_val_2_fastqc.zip'
            - '*_trimmed_fastqc.zip'
    - sortmerna
    - fastqc:
        name: 'FastQC (sortMeRNA)'
        anchor: 'fastqc_sortmerna'
        path_filters:
            - '*_repaired_R1_fastqc.zip'
            - '*_repaired_R2_fastqc.zip'
            - '*_rmrRNA_fastqc.zip'
    - hisat2:
        contents: 'HISAT2 summary stats'
        shared: true
    - htseq
